### ISSUE TITLE
alignment of 'Next' and 'Reset' button 

### ISSUE THREAD

**Issue by rohitsengar001** [DeepakSarwa/Splitter#2]
alignment of 'Next' and 'Reset' button  should be come at middle of the form/screen

**Comment by rohitsengar001** [comment]
![image](https://github.com/DeepakSarwa/Splitter/assets/39033056/b00de219-6ca7-4ff1-a0c5-6a2456234408)
check this image

**Comment by DeepakSarwa** [comment]
Resolved and committed.

**Comment by rohitsengar001** [comment]
once again check its alignments

**Comment by DeepakSarwa** [comment]
Now you can check it once.it's done.

**Comment by rohitsengar001** [comment]
It's appear perfectly.
